javascript_compressor: closure
package_assets: on

javascripts:
  application:
    - public/javascripts/jquery.min.js
    - public/javascripts/pusher.min.js
    - public/javascripts/jquery.autocomplete.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.sexypost.js
    - public/javascripts/sammy-0.6.3.min.js
    - public/javascripts/sammy.push_location_proxy.js
    - public/javascripts/blabbr.js
    - public/javascripts/blabbr.notify.js
    - public/javascripts/ICanHaz.js
    - public/javascripts/application.js
