javascript_compressor: closure
package_assets: on

javascripts:
  application:
    - public/javascripts/jquery-1.5.2.js
    - public/javascripts/pusher.min.js
    - public/javascripts/jquery.autocomplete.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.sexypost.js
    - public/javascripts/sammy.js
    - public/javascripts/blabbr.js
    - public/javascripts/blabbr.notify.js
    - public/javascripts/application.js
