defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: blabbr_dev

test:
  <<: *defaults
  database: blabbr_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: blabbr
