defaults: &defaults
  host: localhost
  persist_in_safe_mode: false

development:
  <<: *defaults
  database: blabbr_dev

test:
  <<: *defaults
  database: blabbr_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
